<?php

/**
 * Implements hook_nagios_info().
 */
function nagios_hook_test_module_nagios_info() {
  return [
    'name' => 'nagios_hook_test_module',
    'id' => 'NAGIOS_CHECK_KEY',
  ];
}

/**
 * Implements hook_nagios().
 */
function nagios_hook_test_module_nagios() {
  return [
    'NAGIOS_CHECK_KEY' => [
      'status' => 1,
      'type' => 'state',
      'text' => 'Text description for the problem',
    ],
  ];
}
